### ISSUE TITLE
Change response code

### ISSUE THREAD

**Issue by ilmila** [glastopf/glastopf#151]
At the moment it's not possible into an emulator to change the HTTP response code, even if it seems that feature implemented.

The function
```python
set_response(self, body, http_code=200, headers=(('Content-type', 'text/html'),)):
```
in HTTPHandler class, accepts the parameter http_code, but it seems ignored.

Functionality:
To be able to change the response code into an emulator, and setting up custom headers.
Tried wiith the following snippet

```python
attack_event.http_request.set_response('', http_code=401, headers=(('WWW-Authenticate', 'realm="XXXXX"'),))
```
but the HTTP response code is "HTTP/1.1 200 OK".

Tried also with the fucntion set_raw_response, without luck.
Any tips?

**Comment by pawel-ch** [comment]
Hi,

I believe this is caused by ignoring status code from previously prepared headers when creating WebOb Response object in [wsgi_wrapper.py](https://github.com/glastopf/glastopf/blob/3.1.2/glastopf/wsgi_wrapper.py#L51)

```python
        for h in header.splitlines():
            if ':' in h:
                h, v = h.split(':', 1)
                res_webob.headers[str(h.strip())] = str(v.strip())
```

This skips the first line of `header`, ie.
```
HTTP/1.0 404 Not Found
```

The quick and little dirty solution could be parsing first line again and setting status code in WebOb Response object by:
```python
res_webob.status = code #404
```
